### ISSUE TITLE
Questions about single image inference

### ISSUE THREAD

**Issue by YimengQiao** [bioturing-org/turing_segment#4] opened 2024-12-19 03:12 UTC
Dear authors, thanks for your great work! A cell segmentation model customized for H&E images is exactly what many people need!

I tried to perform cell segmentation for an H&E image, whose size was `224*224`. I used the following command:

```
turing_segment infer --image-path img/valid/1.000_74_86_raw.png --model-type he --output-dir turing_seg
```

No error has been reported yet, but after the  `he.bin` and `size_he.npz` files were generated, it didn't move anymore, which has lasted for about 12 hours. I tried several times and it still looks like this.
<img width="1467" alt="截屏2024-12-19 10 48 55" src="https://github.com/user-attachments/assets/e8be600d-62b1-4f1f-bc0e-c39a082a0a45" />

The configuration of my server is:
```
NVIDIA GeForce RTX 3090
CUDA 11.8
PyTorch nightly (2.6.0 dev version) with triton 3.2.0
Python 3.10
```

As described in the README.md, I am supposed to obtain a metadata.json and a polygons.parquet, but now I only got `he.bin` and `size_he.npz` and I don't know why this happened. Could you please give me some advice on this? I really appreciate your kind help.

Besides, there is also one thing I want to mention that the codes seem to be only compatible with triton 3.x. I tried some pytorch versions compatible with cuda11.8, and it seemed that only pytorch nightly was compatible with triton 3.x. I am not sure whether it is true, but currently this is the only configuration that can run successfully.

**Comment by tintn** [comment] 2024-12-19 03:42
Hi @YimengQiao, thanks for trying out our package!

It seems the processing is done based on the log, did you see these messages printed:
```
2024-12-19 03:30:26 [INFO] Done segmentation. Found ... cells
2024-12-19 03:30:26 [INFO] Done exporting metadata to ...
2024-12-19 03:30:26 [INFO] Done exporting to ...
```

The `he.bin` and `size_he.npz` files are placed in `models` folder while the results are saved to the folder specified in `--output-dir`. Can you help check that folder?

There should not be any restriction on Triton version as long as it's compatible with the installed PyTorch version. What error did you encounter with the older PyTorch versions?

**Comment by YimengQiao** [comment] 2024-12-19 04:43
Thank you for your prompt response!!

I did not see the above messages printed. The screenshot is all the information I can see so far.

And this is the content of the output directory:
<img width="722" alt="截屏2024-12-19 11 55 00" src="https://github.com/user-attachments/assets/8914dd45-cbc8-4e07-a90f-39981e6fc5e3" />

I think there is no segmentation results file?

For the triton version, at first, I just installed the latest stable pytorch 2.5.1 (with triton 3.1.0) and I got an error that 
```
RuntimeError: Triton Error [CUDA]: device kernel image is invalid
```
I Googled and some people said this might because triton 3.x was not compatible with my driver (470.256.02) or CUDA version and suggested to downgrade the triton.

So then I tried previous stable pytorch 2.x (their corresponding built-in triton versions were triton 2.x) that was compatible with cuda 11.8, the first problem was solved but I got a new error that 
```
ImportError: cannot import name 'triton_key' from 'triton.compiler.compiler'
```
I also found some issues in the pytorch repo about this problem, for example, https://github.com/pytorch/pytorch/issues/127271  and https://github.com/pytorch/pytorch/issues/123042. To be honest, I still don't know the exact reason. I was guessing `triton_key` might be introduced from a newer triton version. And I just followed someone's suggestion on installing pytorch nightly and it worked, where the triton is 3.2.0 (the latest stable triton package is 3.1.0 https://pypi.org/project/triton/).

I am very confused about these dependencies, actually I don't know how this happens, but from what I've tried so far, this is the only configuration that works so I just used that. TvT

**Comment by tintn** [comment] 2024-12-19 05:04
I could not reproduce the issue from my side. Can you try the following:
- Re-run the package with the `--no-compiled` argument. It'll disable the triton-related compilation. If it still doesn't work, can you send us the printed log.
- Can you share the env file: `conda list  > env.txt`

**Comment by YimengQiao** [comment] 2024-12-19 05:42
Thank you so much for your kind help!!!

I re-ran the package with the following command:
```
turing_segment infer --image-path /home/yimeng/projects/cell_segmentation/img/valid/1.000_74_86_raw.png --model-type he --output-dir /home/yimeng/projects/cell_segmentation/turing_seg --no-compiled
```
The program seems to be stuck again, the printed log is:
```
2024-12-19 13:18:30 [WARNING] HE model requires 3 channels. Set to default 0,1,2
2024-12-19 13:18:30 [INFO] Model found at models/he.bin
2024-12-19 13:18:30 [INFO] Load the model at models/he.bin
2024-12-19 13:18:31 [INFO] Scaled checkpoint
2024-12-19 13:18:32 [INFO] Load auto image /home/yimeng/projects/cell_segmentation/img/valid/1.000_74_86_raw.png @ 0 [0, 1, 2], lazy=None
2024-12-19 13:18:32 [INFO] Auto-detected image type: cv2
2024-12-19 13:18:32 [INFO] Size model found at models/size_he.npz
2024-12-19 13:18:32 [INFO] Estimate scale with models/size_he.npz
2024-12-19 13:18:32 [INFO] Cache found for compute_scale at .turing_cache/compute_scale_d1029419de0cbfa480f11aa9fa72e4b32a6e457078db285c7715e4f96e1c05b1.npy
2024-12-19 13:18:32 [INFO] Estimated scale = 2.5266255067220844
2024-12-19 13:18:32 [INFO] Adjusted infer size: 640

  0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/1 [00:01<?, ?it/s, 0]
100%|██████████| 1/1 [00:01<00:00,  1.84s/it, 0]
100%|██████████| 1/1 [00:01<00:00,  1.84s/it, 0]

```
I only got a `he.bin` file and a `size_he.npz` file. The program doesn't terminate itself unless I kill the process manually.

And I exported the env list:
```
# packages in environment at /home/yimeng/miniconda3/envs/turing_segment:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
asciitree                 0.3.3                    pypi_0    pypi
blas                      1.0                         mkl  
brotli-python             1.0.9           py310h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.11.26           h06a4308_0  
certifi                   2024.12.14      py310h06a4308_0  
charset-normalizer        3.3.2              pyhd3eb1b0_0  
cmake                     3.31.2                   pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cuda-version              12.6                          3    nvidia
fasteners                 0.19                     pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.13.1          py310h06a4308_0  
flatbuffers               24.3.25                  pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
fsspec                    2024.10.0                pypi_0    pypi
geopandas                 1.0.1                    pypi_0    pypi
giflib                    5.2.2                h5eee18b_0  
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2           py310heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
humanfriendly             10.0                     pypi_0    pypi
idna                      3.7             py310h06a4308_0  
imagecodecs               2024.9.22                pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306  
jinja2                    3.1.4           py310h06a4308_1  
jpeg                      9e                   h5eee18b_3  
lame                      3.100                h7b6447c_0  
lcms2                     2.16                 hb9589c4_0  
ld_impl_linux-64          2.40                 h12ee557_0  
lerc                      4.0.0                h6a678d5_0  
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.11.1.6                      0    nvidia
libcurand                 10.3.7.77                     0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.22                 h5eee18b_0  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h5eee18b_3  
libidn2                   2.3.4                h5eee18b_0  
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libnpp                    11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                hffd6297_1  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libwebp                   1.3.2                h11a3e52_0  
libwebp-base              1.3.2                h5eee18b_1  
lit                       18.1.8                   pypi_0    pypi
llvm-openmp               14.0.6               h9e868ea_0  
llvmlite                  0.43.0                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_1  
markupsafe                2.1.3           py310h5eee18b_0  
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0           py310h5eee18b_1  
mkl_fft                   1.3.11          py310h5eee18b_0  
mkl_random                1.2.8           py310h1128e8f_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.3.0           py310h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.2.1           py310h06a4308_0  
numba                     0.60.0                   pypi_0    pypi
numcodecs                 0.13.1                   pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
numpy-base                2.0.1           py310hb5e798b_1  
nvidia-cublas-cu11        11.11.3.6                pypi_0    pypi
nvidia-cuda-cupti-cu11    11.8.87                  pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.8.89                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.8.89                  pypi_0    pypi
nvidia-cudnn-cu11         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.3.0.86                pypi_0    pypi
nvidia-cusolver-cu11      11.4.1.48                pypi_0    pypi
nvidia-cusparse-cu11      11.7.5.86                pypi_0    pypi
nvidia-ml-py              12.560.30                pypi_0    pypi
nvidia-nccl-cu11          2.21.5                   pypi_0    pypi
nvidia-nvtx-cu11          11.8.86                  pypi_0    pypi
onnx                      1.17.0                   pypi_0    pypi
onnxruntime-gpu           1.18.0                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.5.2                he7f1fd0_0  
openssl                   3.0.15               h5eee18b_0  
packaging                 24.2                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
pillow                    11.0.0          py310hcea889d_1  
pip                       24.2            py310h06a4308_0  
protobuf                  5.29.1                   pypi_0    pypi
pyarrow                   18.1.0                   pypi_0    pypi
pyogrio                   0.10.0                   pypi_0    pypi
pyproj                    3.7.0                    pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.16              he870216_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-cuda              11.8                 h7e8668a_6    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytorch-triton            3.2.0+gitf9cdf582          pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2           py310h5eee18b_0  
readline                  8.2                  h5eee18b_0  
requests                  2.32.3          py310h06a4308_1  
scipy                     1.14.1                   pypi_0    pypi
setuptools                75.1.0          py310h06a4308_0  
shapely                   2.0.6                    pypi_0    pypi
six                       1.17.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
sympy                     1.13.1                   pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
tifffile                  2024.12.12               pypi_0    pypi
tk                        8.6.14               h39e8969_0  
torch                     2.6.0.dev20241218+cu118          pypi_0    pypi
torchaudio                2.6.0.dev20241218+cu118          pypi_0    pypi
torchvision               0.22.0.dev20241218+cu118          pypi_0    pypi
tqdm                      4.67.1                   pypi_0    pypi
turing-segment            0.3.1                    pypi_0    pypi
typing_extensions         4.11.0          py310h06a4308_0  
tzdata                    2024.2                   pypi_0    pypi
urllib3                   2.2.3           py310h06a4308_0  
wheel                     0.44.0          py310h06a4308_0  
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
zarr                      2.18.3                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  
zstd                      1.5.6                hc292b87_0  
```

**Comment by tintn** [comment] 2024-12-19 07:07
We are having trouble reproducing the issue, it does not occur on all of our test environments. 

Can you try to run it on Google Colab to check if the issue is from the code itself or the environment, please check this example (please remove `--channel-last` argument if your image is channel first):
![image (5)](https://github.com/user-attachments/assets/0b858b60-47f7-4ea0-ba65-1b7a1feb9bad)

**Comment by YimengQiao** [comment] 2024-12-19 07:42
It worked well on Colab. I think the issue is from my environment. It is really confusing and I will check that later. I really appreciate your kind help!

**Comment by tintn** [comment] 2024-12-19 08:26
You are welcome! Close the issue for now. Feel free to re-open it or create a new one if you run into any issue

**Closed by tintn** 2024-12-19 08:26 UTC
